name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests:
    name: Test tool
    runs-on: ${{ matrix.os }}
    # needs: formatting-check
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          # - "macos-latest"
          # - "windows-latest"
        node-version:
          - "20.x"
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm install

      - name: Run test
        run: npm test
